name: biyi
description: A convenient translation and dictionary app written in Flutter.
publish_to: 'none'
version: 0.4.0+10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  audioplayers: ^0.20.1
  bot_toast: ^4.0.1
  device_info_plus: ^3.1.1
  dio: ^4.0.4
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  fluentui_system_icons: ^1.1.153
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.23.0+1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hotkey_manager: ^0.1.5
  launch_at_startup: ^0.1.7
  libwinmedia: ^0.0.7
  package_info_plus: ^1.4.0
  page_transition: ^2.0.4
  photo_view: ^0.13.0
  protocol_handler: ^0.1.1
  reorderables: ^0.4.4
  screen_capturer: ^0.1.2
  screen_retriever: ^0.1.0
  screen_text_extractor: ^0.1.2
  shortid: ^0.1.2
  sticky_headers: ^0.2.0
  tray_manager: ^0.1.3
  uni_ocr: ^0.1.0
  uni_translate: ^0.1.1
  url_launcher: ^6.0.17
  window_manager: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

dependency_overrides:
  # https://github.com/fluttercommunity/plus_plugins/issues/760
  package_info_plus_windows:
    git:
      url: https://github.com/fluttercommunity/plus_plugins.git
      ref: main
      path: packages/package_info_plus/package_info_plus_windows
  uni_ocr:
    path: ../uni_ocr/packages/uni_ocr
  uni_ocr_client:
    path: ../uni_ocr/packages/uni_ocr_client
  uni_translate:
    path: ../uni_translate/packages/uni_translate
  uni_translate_client:
    path: ../uni_translate/packages/uni_translate_client
  translation_engine_baidu:
    path: ../uni_translate/packages/translation_engine_baidu
  translation_engine_caiyun:
    path: ../uni_translate/packages/translation_engine_caiyun
  translation_engine_deepl:
    path: ../uni_translate/packages/translation_engine_deepl
  translation_engine_google:
    path: ../uni_translate/packages/translation_engine_google
  translation_engine_iciba:
    path: ../uni_translate/packages/translation_engine_iciba
  translation_engine_tencent:
    path: ../uni_translate/packages/translation_engine_tencent
  translation_engine_youdao:
    path: ../uni_translate/packages/translation_engine_youdao
  ocr_engine_builtin:
    path: ../uni_ocr/packages/ocr_engine_builtin
  ocr_engine_youdao:
    path: ../uni_ocr/packages/ocr_engine_youdao
  platform_context_menu:
    path: ../../leanflutter/platform_context_menu

flutter:
  uses-material-design: false

  assets:
    - assets/images/
    - assets/images/flag_icons/
    - assets/images/ocr_engine_icons/
    - assets/images/translation_engine_icons/
    - assets/translations/
