name: biyi_app
description: A convenient translation and dictionary app written in dart / Flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.3.3+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  audioplayers: ^0.19.1
  bot_toast: ^4.0.1
  device_info_plus: ^3.1.0
  dio: ^4.0.0
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  hotkey_manager: ^0.1.4
  libwinmedia: ^0.0.5
  package_info_plus: ^1.0.4
  photo_view: ^0.12.0
  pro_account:
    git:
      ref: main
      url: https://github.com/biyidev/pro_account_noop.git
  screen_retriever: ^0.0.2
  # screen_text_extractor: ^0.0.1
  screen_text_extractor:
    git:
      ref: main
      url: https://github.com/leanflutter/screen_text_extractor.git
  sticky_headers: ^0.1.8
  tray_manager: ^0.1.0
  uni_links: ^0.5.1
  uni_links_macos:
    git:
      path: packages/uni_links_macos
      ref: master
      url: https://github.com/biyidev/dart_pkgs.git
  uni_ocr:
    git:
      path: packages/uni_ocr
      ref: master
      url: https://github.com/biyidev/uni_ocr.git
  uni_ocr_client:
    git:
      path: packages/uni_ocr_client
      ref: master
      url: https://github.com/biyidev/uni_ocr.git
  uni_translate:
    git:
      path: packages/uni_translate
      ref: master
      url: https://github.com/biyidev/uni_translate.git
  uni_translate_client:
    git:
      path: packages/uni_translate_client
      ref: master
      url: https://github.com/biyidev/uni_translate_client.git
  url_launcher: ^6.0.6
  uuid: ^3.0.4
  window_manager: ^0.0.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

  archive: ^3.1.5
  msix: ^2.1.3

dependency_overrides:
  # hotkey_manager:
  #   path: ../../leanflutter/hotkey_manager
  # pro_account:
  #   path: ../pro_account
  # screen_retriever:
  #   path: ../../leanflutter/screen_retriever
  # screen_text_extractor:
  #   path: ../../leanflutter/screen_text_extractor
  # tray_manager:
  #   path: ../../leanflutter/tray_manager
  uni_ocr:
    path: ../uni_ocr/packages/uni_ocr
  uni_ocr_client:
    path: ../uni_ocr/packages/uni_ocr_client
  uni_translate:
    path: ../uni_translate/packages/uni_translate
  uni_translate_client:
    path: ../uni_translate/packages/uni_translate_client
  # window_manager:
  #   path: ../../leanflutter/window_manager

flutter:
  uses-material-design: true

  assets:
    - assets/environments/
    - assets/images/
    - assets/images/flag_icons/
    - assets/images/ocr_engine_icons/
    - assets/images/translation_engine_icons/
    - assets/translations/

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
