name: biyi_advanced_features
description: biyi advanced features
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  crypto: ^3.0.3
  device_info_plus: ^9.0.1
  dio: ^5.1.2
  flutter:
    sdk: flutter
  package_info_plus: ^4.0.1
  uni_ocr_client: ^0.1.1
  uni_translate_client: ^0.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
