name: biyi_api_client
description: biyi api client
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  dio: ^5.1.2
  json_annotation: ^4.8.0
  uni_ocr_client: ^0.1.1
  uni_translate_client: ^0.1.6

dev_dependencies:
  build_runner: ^2.4.4
  json_serializable: ^6.6.0
  mostly_reasonable_lints: ^0.1.2
