name: biyi_app
description: A convenient translation and dictionary app written in Flutter.
homepage: https://github.com/lijy91/biyi
publish_to: "none"
version: 0.5.0+21
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.6"

dependencies:
  audioplayers: ^5.2.1
  biyi_advanced_features:
    path: ../../packages/biyi_advanced_features
  biyi_api_client:
    path: ../../packages/biyi_api_client
  bot_toast: ^4.1.3
  collection: ^1.18.0
  fluentui_system_icons: ^1.1.255
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.7+2
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  go_router: ^16.3.0
  hotkey_manager: ^0.2.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  keypress_simulator: ^0.2.0
  launch_at_startup: ^0.3.1
  ocr_engine_builtin: ^0.1.1
  ocr_engine_youdao: ^0.1.1
  package_info_plus: ^9.0.0
  path: ^1.8.3
  path_provider: ^2.1.1
  protocol_handler: ^0.1.6
  provider: ^6.1.1
  reorderables: ^0.6.0
  screen_capturer: ^0.2.2
  screen_text_extractor: ^0.1.3
  shortid: ^0.1.2
  slang: ^4.9.2
  slang_flutter: ^4.9.0
  sticky_headers: ^0.3.0+2
  translation_engine_baidu: ^0.1.6
  translation_engine_caiyun: ^0.1.6
  translation_engine_deepl: ^0.1.6
  translation_engine_google: ^0.1.6
  translation_engine_iciba: ^0.1.6
  translation_engine_openai: ^0.1.6
  translation_engine_tencent: ^0.1.6
  translation_engine_youdao: ^0.1.6
  tray_manager: ^0.2.1
  uikit: 0.1.0
  uni_ocr_client: ^0.1.1
  uni_platform: ^0.1.0
  uni_translate_client: ^0.1.7
  url_launcher: ^6.2.2
  vclibs: ^0.1.0
  nativeapi: ^0.1.0

dev_dependencies:
  beyondtranslate_lints: ^0.1.0
  build_runner: ^2.10.1
  dependency_validator: ^3.2.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  go_router_builder: ^4.0.1
  slang_build_runner: ^4.9.0

dependency_overrides:
  cnativeapi:
    path: ../../../../libnativeapi/nativeapi-flutter/packages/cnativeapi
  nativeapi:
    path: ../../../../libnativeapi/nativeapi-flutter/packages/nativeapi
  shadcn_flutter:
    path: ../../../../owncal/shadcn_flutter

flutter:
  uses-material-design: false
  assets:
    - resources/images/
    - resources/images/flag_icons/
    - resources/images/ocr_engine_icons/
    - resources/images/translation_engine_icons/
